portaria/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from database.db_connection import mysql
import MySQLdb.cursors

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        # Captura o usuário e senha enviados pelo formulário
        nome_usuario = request.form['nome_usuario']
        senha_usuario = request.form['senha_usuario']

        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)

        # Busca no banco se existe um usuário com o nome e senha informados
        cursor.execute('SELECT * FROM usuarios WHERE nome_usuario = %s AND senha_usuario = %s', (nome_usuario, senha_usuario))
        account = cursor.fetchone() # Pega o primeiro registro encontrado

        # Se encontrou o usuário o login cria variáveis de sessão indicando que o usuário está logado
        if account:
            session['loggedin'] = True
            session['id'] = account['id']
            session['nome_usuario'] = account['nome_usuario']
            return redirect(url_for('dashboard.dashboard'))
        else:
            flash('Usuário ou senha inválidos!', 'danger')

    # Sempre que for acesso GET, ou quando o login falha, renderiza a página de login
    return render_template('login.html')

@auth_bp.route('/logout')
def logout():
    session.clear() # Remove todas as informações da sessão
    return redirect(url_for('auth.login'))  # Redireciona para a tela de login

portaria/routes/dashboard.py
from flask import Blueprint, render_template, session, redirect, url_for, jsonify
from .models import Morador, Veiculo, Acesso, db, AcessoVisitante
from datetime import datetime, timedelta, date

dashboard_bp = Blueprint('dashboard', __name__)

# Primeiro verifica se o usuário está logado via session. Se não, redireciona para a tela de login.
@dashboard_bp.route('/dashboard')
def dashboard():
    if 'loggedin' not in session:
        return redirect(url_for('auth.login'))
    # Cards
    total_moradores = Morador.query.count()
    total_veiculos = Veiculo.query.count()
    nome_usuario = session['nome_usuario']

    # Últimos 10 acessos de moradores e visitantes
    acessos_moradores = Acesso.query.order_by(Acesso.id.desc()).limit(10).all()
    acessos_visitantes = AcessoVisitante.query.order_by(AcessoVisitante.id.desc()).limit(10).all()
    # Criar lista unificada normalizada
    acessos_recentes = []

    # Acessos recentes por reconhecimento facial - Lista de Moradores
    for a in acessos_moradores:
        acessos_recentes.append({
            "tipo": "morador",
            "nome": a.morador.nome_morador,
            "apto": a.morador.apartamento_morador,
            "data": a.data_registro.strftime('%d/%m'),
            "hora": a.hora_registro.strftime('%H:%M'),
            "codigo": None
        })

    # Acessos recentes por código - Lista de Visitantes
    for v in acessos_visitantes:
        acessos_recentes.append({
            "tipo": "visitante",
            "nome": None,
            "apto": None,
            "data": v.data_hora.strftime('%d/%m'),
            "hora": v.data_hora.strftime('%H:%M'),
            "codigo": v.codigo_id
        })

    # Ordenar por data e hora (mais recente primeiro)
    acessos_recentes = sorted(
        acessos_recentes,
        key=lambda x: (x["data"], x["hora"]),
        reverse=True
    )[:10]

    # Visitantes do dia
    hoje = date.today()
    visitantes_hoje = AcessoVisitante.query.filter(
        db.func.date(AcessoVisitante.data_hora) == hoje
    ).count()

    # No final da função, esses valores são enviados ao template
    return render_template(
        'dashboard.html',
        nome_usuario=nome_usuario,
        total_moradores=total_moradores,
        total_veiculos=total_veiculos,
        acessos_recentes=acessos_recentes,
        visitantes_hoje=visitantes_hoje
    )

# Rota que retorna dados do gráfico em JSON
@dashboard_bp.route('/dashboard/dados_grafico')
def dados_grafico():
    dias = 7 # define que serão 7 dias
    hoje = datetime.now().date() # calcula a data de hoje
    inicio = hoje - timedelta(days=dias - 1) # Calcula a data inicial (hoje - 6 dias)

    # Busca acessos de moradores
    resultados_moradores = (
        db.session.query(Acesso.data_registro, db.func.count(Acesso.id))
        .filter(Acesso.data_registro.between(inicio, hoje))
        .group_by(Acesso.data_registro)
        .order_by(Acesso.data_registro)
        .all()
    )

    acessos_moradores = {r[0]: r[1] for r in resultados_moradores}

    # Busca acessos de visitantes (código)
    resultados_visitantes = (
        db.session.query(db.func.date(AcessoVisitante.data_hora), db.func.count(AcessoVisitante.id)) # seleciona data e quantidade de acessos
        .filter(db.func.date(AcessoVisitante.data_hora).between(inicio, hoje)) # pega somente os acessos dentro dos últimos 7 dias
        .group_by(db.func.date(AcessoVisitante.data_hora)) # agrupa por data
        .order_by(db.func.date(AcessoVisitante.data_hora)) # conta quantos acessos teve por dia
        .all()
    )

    acessos_visitantes = {r[0]: r[1] for r in resultados_visitantes}

    # UNIFICA MORADORES + VISITANTES - Monta lista de todas as datas
    todas_as_datas = [inicio + timedelta(days=i) for i in range(dias)]

    labels = [data.strftime('%d/%m') for data in todas_as_datas] # Constrói os labels (datas no gráfico)
    valores = [ # Soma morador + visitante
        acessos_moradores.get(data, 0) + acessos_visitantes.get(data, 0)
        for data in todas_as_datas
    ]

    return jsonify({'labels': labels, 'valores': valores})

portaria/routes/historico.py
from flask import Blueprint, render_template, request
from .models import Historico

historico_bp = Blueprint('historico_bp', __name__, url_prefix='/historico')

@historico_bp.route('/', methods=['GET'])
def listar_historico():
    # Captura o termo de busca enviado pela URL (?q=alguma coisa)
    termo = request.args.get("q", "").strip()
    query = Historico.query  # Começa uma consulta base na tabela Historico

# Se o usuário digitou algo para buscar
    if termo:
        termo_like = f"%{termo}%"
        # Filtro: busca por ação que contenham o termo
        query = query.filter(
            (Historico.usuario.ilike(termo_like)) |
            (Historico.acao.ilike(termo_like))
        )

    # Ordena os resultados por ID (do mais recente para o mais antigo)
    historico_lista = query.order_by(Historico.id.desc()).all()

    # Envia os dados para o template historico.html
    return render_template(
        'historico.html',
        historico=historico_lista,
        termo=termo
    )
    

portaria/routes/moradores.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app, jsonify, session
from .models import db, Morador, Veiculo, registrar_historico
import os, base64, json

moradores_bp = Blueprint('moradores_bp', __name__, url_prefix='/moradores')

# Carrega todos os moradores e envia para o template
@moradores_bp.route('/')
def listar_moradores():
    moradores_lista = Morador.query.all()
    return render_template('moradores.html', moradores=moradores_lista)

# morador=None indica que é cadastro, não edição
@moradores_bp.route('/novo')
def novo():
    return render_template('moradores_form.html', morador=None)

# Salvar morador + veículo (Lê os campos enviados pelo formulário)
@moradores_bp.route('/salvar', methods=['POST'])
def salvar():
    nome = request.form['nome_morador']
    email = request.form['email_morador']
    cpf = request.form['cpf_morador']
    telefone = request.form['telefone_morador']
    nascimento = request.form['nascimento_morador']
    apartamento = request.form['apartamento_morador']
    bloco = request.form['bloco_morador']
    moradia = request.form['moradia_morador']
    quantidade = request.form['quantidade_morador']

    # Verifica duplicados de morador
    if Morador.query.filter_by(cpf_morador=cpf).first():
        flash("Já existe morador com este CPF!", "warning")
        return redirect(url_for('moradores_bp.novo'))
    if Morador.query.filter_by(email_morador=email).first():
        flash("Já existe morador com este E-mail!", "warning")
        return redirect(url_for('moradores_bp.novo'))
    if Morador.query.filter_by(telefone_morador=telefone).first():
        flash("Já existe morador com este Telefone!", "warning")
        return redirect(url_for('moradores_bp.novo'))

    # Veículo (opcional)
    placa = request.form.get('placa')
    modelo = request.form.get('modelo')
    cor = request.form.get('cor')

    # Se o morador cadastrar um veículo, valida se a placa já existe
    if placa and Veiculo.query.filter_by(placa=placa).first():
        flash("Já existe morador com esta Placa de veículo!", "warning")
        return redirect(url_for('moradores_bp.novo'))

    # Criar objeto Morador (ainda não salva)
    morador = Morador(
        nome_morador=nome,
        email_morador=email,
        cpf_morador=cpf,
        telefone_morador=telefone,
        nascimento_morador=nascimento,
        apartamento_morador=apartamento,
        bloco_morador=bloco,
        moradia_morador=moradia,
        quantidade_morador=quantidade
    )

    # Foto - O front envia a foto em base64.
    foto_data = request.form.get('foto_morador_data')
    if foto_data:
        header, encoded = foto_data.split(",", 1)
        foto_bytes = base64.b64decode(encoded)
        nome_arquivo = f"{nome.replace(' ', '_')}.png"
        caminho = os.path.join(current_app.static_folder, 'uploads', nome_arquivo)
        with open(caminho, 'wb') as f:
            f.write(foto_bytes)
        morador.foto_morador = nome_arquivo

    # Salvar face descriptor (reconhecimento facial)
    face_descriptor_json = request.form.get('face_descriptor')
    if face_descriptor_json:
        morador.face_descriptor = face_descriptor_json

    # Criar veículo (se foi enviado)
    if placa:
        veiculo = Veiculo(
            placa=placa,
            modelo=modelo,
            cor=cor,
            apartamento=apartamento,
            morador=morador
        )
        db.session.add(veiculo)
    # Salvar tudo no banco
    db.session.add(morador)
    db.session.commit()

    # Salvar ação no histórico
    nome_usuario = session.get('nome_usuario', 'Administrador')
    registrar_historico(nome_usuario, f"Cadastrou morador '{nome}'", "Moradores")

    flash("Morador cadastrado com sucesso!", "success")
    return redirect(url_for('moradores_bp.listar_moradores'))

# Editar morador
@moradores_bp.route('/editar/<int:id>')
def editar(id):
    morador = Morador.query.get_or_404(id) # aqui o Flask pega o morador do banc
    return render_template('moradores_form.html', morador=morador) # EDITAR = MORADOR=MORADOR

# Atualizar morador
@moradores_bp.route('/atualizar', methods=['POST'])
def atualizar():
    id = request.form['id']
    morador = Morador.query.get_or_404(id)

    morador.nome_morador = request.form['nome_morador']
    morador.email_morador = request.form['email_morador']
    morador.cpf_morador = request.form['cpf_morador']
    morador.telefone_morador = request.form['telefone_morador']
    morador.nascimento_morador = request.form['nascimento_morador']
    morador.apartamento_morador = request.form['apartamento_morador']
    morador.bloco_morador = request.form['bloco_morador']
    morador.moradia_morador = request.form['moradia_morador']
    morador.quantidade_morador = request.form['quantidade_morador']

    # Foto
    foto_data = request.form.get('foto_morador_data')
    if foto_data:
        header, encoded = foto_data.split(",", 1)
        foto_bytes = base64.b64decode(encoded)
        nome_arquivo = f"{morador.nome_morador.replace(' ', '_')}.png"
        caminho = os.path.join(current_app.static_folder, 'uploads', nome_arquivo)
        with open(caminho, 'wb') as f:
            f.write(foto_bytes)
        morador.foto_morador = nome_arquivo

    # Face descriptor
    face_descriptor_json = request.form.get('face_descriptor')
    if face_descriptor_json:
        morador.face_descriptor = face_descriptor_json

    # Veículo
    placa = request.form.get('placa')
    modelo = request.form.get('modelo')
    cor = request.form.get('cor')

    if placa:
        if morador.veiculos:
            veiculo = morador.veiculos[0]  # assume 1 veículo
            veiculo.placa = placa
            veiculo.modelo = modelo
            veiculo.cor = cor
            veiculo.apartamento = morador.apartamento_morador
        else:
            veiculo = Veiculo(
                placa=placa,
                modelo=modelo,
                cor=cor,
                apartamento=morador.apartamento_morador,
                morador=morador
            )
            db.session.add(veiculo)

    db.session.commit()

    # Histórico
    nome_usuario = session.get('nome_usuario', 'Administrador')
    registrar_historico(nome_usuario, f"Editou morador '{morador.nome_morador}'", "Moradores")

    flash("Morador atualizado com sucesso!", "success")
    return redirect(url_for('moradores_bp.listar_moradores'))

# Excluir morador
@moradores_bp.route('/excluir/<int:id>')
def excluir(id):
    morador = Morador.query.get_or_404(id)

    # Caminho da imagem
    if morador.foto_morador:
        caminho_foto = os.path.join(current_app.static_folder, 'uploads', morador.foto_morador)
        # Remove o arquivo se ele existir
        if os.path.exists(caminho_foto):
            os.remove(caminho_foto)

    # Exclui o morador (e automaticamente o veículo se tiver relacionamento cascade)
    # Guarda o nome antes de deletar
    nome_morador = morador.nome_morador

    db.session.delete(morador)
    db.session.commit()

    # Histórico
    nome_usuario = session.get('nome_usuario', 'Administrador')
    registrar_historico(nome_usuario, f"Excluiu morador '{nome_morador}'", "Moradores")

    flash("Morador excluído com sucesso!", "success")
    return redirect(url_for('moradores_bp.listar_moradores'))

# Rota para enviar descritores para o JS
@moradores_bp.route('/descriptors')
def get_descriptors():
    try:
        moradores = Morador.query.all()
        lista = []
        for m in moradores:
            if m.face_descriptor:  # só envia quem tem descritor
                lista.append({
                    "id": m.id,
                    "nome": m.nome_morador,
                    "descriptor": json.loads(m.face_descriptor)  # converte string JSON para array
                })
        return jsonify(lista)
    except Exception as e:
        return jsonify({"error": "Erro ao buscar descritores do banco.", "msg": str(e)}), 500

portaria/routes/notificacoes.py
from flask import Blueprint, render_template

notificacoes_bp = Blueprint(
    'notificacoes_bp',
    __name__,
    url_prefix='/notificacoes'
)

# Página principal de notificações
@notificacoes_bp.route('/')
def notificacoes():
    return render_template('notificacoes.html')

portaria/routes/veiculos.py
from flask import Blueprint, render_template, session, request
from .models import Veiculo, Morador  # importa também o modelo do morador

veiculos_bp = Blueprint('veiculos_bp', __name__, url_prefix='/veiculos')

@veiculos_bp.route('/', methods=['GET'])
def listar_veiculos():

     # Captura o termo que veio pela URL na busca
    termo = request.args.get("q", "").strip()
    # Começa a montar a consulta padrão (sem filtros ainda)
    query = Veiculo.query

    if termo:
        termo_like = f"%{termo}%"
        # Adiciona filtros
        query = query.filter( # aplica o filtro
            (Veiculo.placa.ilike(termo_like)) |
            (Veiculo.modelo.ilike(termo_like)) |
            (Veiculo.cor.ilike(termo_like)) |
            (Veiculo.morador.has(Morador.nome_morador.ilike(termo_like)))
        )

    # Executa a query e pega os veículos encontrados e quantidade
    veiculos_lista = query.all()
    total_veiculos = query.count()
    nome_usuario = session.get('nome_usuario', 'Usuário')

    # Renderiza o template 'veiculos.html' enviando os dados para uso na tela
    return render_template(
        'veiculos.html',
        veiculos=veiculos_lista,
        total_veiculos=total_veiculos,
        nome_usuario=nome_usuario,
        termo=termo  # opcional, para reaproveitar no input
    )

portaria/templates/base.html
{% set current_path = request.path %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema ERP</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/boxicons/2.1.1/css/boxicons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">

    <!-- Bloco para adicionar CSS específico de cada página -->
    {% block css %}{% endblock %}
</head>
<body>

<div class="wrapper">
  {% block navbar %}
  <nav id="sidebar" class="sidebar d-flex flex-column text-white" style="border-right: 1px solid rgb(200, 200, 200);">
    <div class="d-flex justify-content-between align-items-center px-3" >
     <img id="logo-img" src="{{ url_for('static', filename='imagens/img-logo/horizontal-branca.jpg') }}" style="width: 10.5rem; margin-top: 17px; margin-left: 10px;">
        <button class="btn mt-3" id="sidebarMinimize">
          <i class="bi bi-chevron-double-left text-black"></i>
        </button>
    </div>

    <hr style="color: rgb(134, 134, 134);">

    <ul class="nav nav-pills flex-column mb-auto mt-3">
      <span class="nav-title" style="color: rgb(134, 134, 134); margin-left: 40px; font-size: 14px;">NAVEGAÇÃO</span>
  
<li>
  <!-- se o usuario clicar no url_for do dashboard ele muda de cor, se nao, fica texto branco -->
  <a href="{{ url_for('dashboard.dashboard') }}" class="nav-link {% if current_path == url_for('dashboard.dashboard') %}active{% else %}text-black{% endif %} mt-2">
    <i class='bi bi-house-door me-2 fs-6'></i> 
    <span class="menu-text">Dashboard</span>
  </a>
</li>

<li>
  <a href="{{ url_for('moradores_bp.listar_moradores') }}" class="nav-link {% if 'moradores' in current_path %}active{% else %}text-black{% endif %} mt-2">
    <i class='bi bi-person me-2 fs-6'></i> 
    <span class="menu-text">Moradores</span>
  </a>
</li>

<li>
  <a href="{{ url_for('veiculos_bp.listar_veiculos') }}" class="nav-link {% if 'veiculos' in current_path %}active{% else %}text-black{% endif %} mt-2">
    <i class='bi bi-car-front me-2 fs-6'></i> 
    <span class="menu-text">Veículos</span>
  </a>
</li>

<li>
  <a href="{{ url_for('historico_bp.listar_historico') }}" class="nav-link {% if 'historico' in current_path %}active{% else %}text-black{% endif %} mt-2">
    <i class='bi bi-arrow-counterclockwise me-2 fs-6'></i>
    <span class="menu-text">Histórico</span>
  </a>
</li>

</ul>

<ul class="nav nav-pills flex-column mb-auto mt-3">
      <span class="nav-title" style="color: rgb(134, 134, 134); margin-left: 40px; font-size: 14px;">STATUS DO SISTEMA</span>
      <li>
        <a class="nav-link {% if 'sistemaonline' in current_path %}active{% else %}text-black{% endif %} mt-2">
          <i class='bi bi-circle-fill me-2' style="color: rgb(6, 182, 6); font-size: 8px;"></i>
          <span class="menu-text">Sistema online</span>
        </a>
      </li>

      <li>
        <a href="{{ url_for('notificacoes_bp.notificacoes') }}" class="nav-link {% if 'notificacoes' in current_path %}active{% else %}text-black{% endif %} mt-2">
          <i class='bi bi-bell me-2 fs-6'></i> 
          <span class="menu-text">Notificações</span>
        </a>
      </li>
</ul>
  
<div class="mt-auto mb-4">
  <ul class="nav nav-pills flex-column mt-auto">
    <li><a href="{{ url_for('auth.logout') }}" class="nav-link text-black"><i class='bi bi-arrow-left-circle me-2 fs-6'></i><span class="menu-text">Sair</span></a></li>
  </ul>
</div>
  </nav>

  {% endblock %}  

  <div class="main-content {% block main_content_class %}{% endblock %}">
    {% block content %}{% endblock %}

    {% block footer %}
    <footer class="footer">
      <p class="mt-1" >&copy; 2025 NextSoft Technology. Todos os direitos reservados.</p>
    </footer>
  {% endblock %}
    
  </div>
</div>

  <script src="{{ url_for('static', filename='js/base.js') }}"></script>
    
</body>
</html>

portaria/templates/historico.html
{% extends "base.html" %}

{% block content %}

<nav class="navbar" style="padding: 10px 24px;">
  <a class="navbar-brand">
    <div class="navbar-brand fw-bold mt-2" style="font-size: 35px; color: rgb(27, 27, 27);">Histórico</div>
  </a>
</nav>

<main class="container-fluid px-4 fade-in">

<br>

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }} text-center w-50 mx-auto mt-3" style="background-color: #DBEAFF; color: #2f60e6; border: 1px solid #2f60e6;">
        <p style="margin: 0;">{{ message }}</p>
        <button type="button" class="btn-close position-absolute end-0 top-50 translate-middle-y me-2" data-bs-dismiss="alert" aria-label="Fechar"></button>
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}

<div class="info d-flex mt-2" 
     style="background-color: #fff; padding: 13px; border-radius: 12px;
            box-shadow: 2px 5px 8px rgba(0, 0, 0, 0.1);">

  <div class="navbar-container" style="flex: 1; width: 100%;"> 
    <form method="GET" action="{{ url_for('historico_bp.listar_historico') }}" style="width: 100%;">
      <div class="search-container" 
           style="display: flex; align-items: center; border: 1px solid #c3c3c3;
                  border-radius: 4px; padding: 5px; margin-right: 10px; width: 100%;">
        <i class="bi bi-search ms-2 me-2 fs-6" style="color: #838282e8;"></i>
        <input type="text" name="q"
               style="padding: 5px; font-size: 16px; border: none; border-radius: 4px; width: 100%;" 
               placeholder="Pesquisar por ação..."
               value="{{ request.args.get('q', '') }}">
      </div>
    </form>
  </div>
</div>

<br>

<div class="ag-courses-item_bg"></div>

  <div class="table-responsive" 
     style="max-height: 450px; overflow-y: auto; border-radius: 8px;"> <!-- SCROLL - Barra de rolagem -->
    <table class="table table-striped table-bordered align-middle">
      <thead class="table" style="font-size: 14px; border: 1px rgba(134, 134, 134, 0.473);">
        <tr>
          <th class="py-3 text-center">USUÁRIO</th>
          <th class="py-3 text-center">AÇÃO</th>
          <th class="py-3 text-center">ENTIDADE</th>   
          <th class="py-3 text-center">DATA</th>
          <th class="py-3 text-center">HORA</th>
        </tr>
      </thead>

      <tbody>
            {% for item in historico %}
            <tr>
                <td class="py-3">{{ item.usuario }}</td>
                <td class="py-3">{{ item.acao }}</td>
                <td class="py-3">{{ item.entidade }}</td>
                <td class="py-3">{{ item.data_registro.strftime('%d/%m/%Y') }}</td>
                <td class="py-3">{{ item.hora_registro.strftime('%H:%M:%S') }}</td>
            </tr>
            {% else %}
        <tr>
          <td colspan="5" class="text-center">Nenhum registro encontrado.</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
  </div>

</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}

portaria/templates/moradores.html
{% extends "base.html" %}

{% block content %}

<!-- Moradores -->
<nav class="navbar" style="padding: 10px 24px;">
  <a class="navbar-brand">
    <div class="navbar-brand fw-bold mt-2" style="font-size: 35px; color: rgb(27, 27, 27);">Sistema de Cadastro</div>
  </a>
</nav>

<main class="container-fluid px-4 fade-in">

<br>

<a href="{{ url_for('moradores_bp.novo') }}" class="btn btn-outline-purple mb-2">
  <i class="bi bi-person-plus ms-1 me-2"></i> Novo Morador
</a>

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }} text-center w-50 mx-auto mt-3" style="background-color: #DBEAFF; color: #2f60e6; border: 1px solid #2f60e6;">
        <p style="margin: 0;">{{ message }}</p>
        <button type="button" class="btn-close position-absolute end-0 top-50 translate-middle-y me-2" data-bs-dismiss="alert" aria-label="Fechar"></button>
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}

<!-- Tabela dos moradores cadastrados -->

  <div class="table-responsive"
    style="max-height: 500px; overflow-y: auto; border-radius: 8px;"> <!-- SCROLL - Barra de rolagem -->
    <table class="table table-striped table-bordered align-middle">
      <thead class="table" style="font-size: 14px; border: 1px rgba(134, 134, 134, 0.473);">
        <tr>
          <th class="py-3 text-center">ID</th>
          <th class="py-3 text-center">NOME</th>
          <th class="py-3 text-center">TELEFONE</th>   
          <th class="py-3 text-center">EMAIL</th>
          <th class="py-3 text-center">AÇÕES</th>
        </tr>
      </thead>

      <tbody>
            {% for morador in moradores %}
            <tr>
                <td class="py-3">{{ morador.id }}</td>
                <td class="py-3">{{ morador.nome_morador}}</td>
                <td class="py-3">{{ morador.telefone_morador }}</td>
                <td class="py-3">{{ morador.email_morador }}</td>
                
                <td class="text-nowrap">
                   
                    <!-- Botão de exclusão -->
                    <a href="{{ url_for('moradores_bp.excluir', id=morador.id) }}" class="btn btn-dark btn-sm"
                        onclick="return confirm('Tem certeza que deseja excluir?')">
                        <i class="bi bi-trash"></i>
                    </a>

                    <!-- Botão de edição -->
                    <a href="{{ url_for('moradores_bp.editar', id=morador.id) }}" class="btn btn-light btn-sm me-1" style="border-color: #83828238;">
                        <i class="bi bi-pencil"></i>
                    </a>
                </td>
              </tr>
            {% endfor %}
        </tbody>
    </table>
  </div>
</main>

<style>
  @media (max-width: 768px) {
  /* Quebra de linha no título "Sistema de Cadastro" */
  .navbar .navbar-brand .fw-bold {
    white-space: normal !important; /* permite quebra */
    font-size: 28px !important;     /* diminui um pouco */
    line-height: 1.2;
  }
}
</style>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}